# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: aeto
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "amd64"
      - "arm64"
archives:
  - id: aeto
    builds:
      - aeto
    replacements:
      darwin: Darwin
      linux: Linux
    files:
      - README*
      - LICENCE*
      - config/crd/*
      - config/rbac/*
      - config/manager/*
      - config/prometheus/*
      - config/default/*
      - config/default-resources/*
      - config/samples/*
dockers:
  - id: docker_amd64
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: "Dockerfile.goreleaser"
    image_templates:
      - "kristofferahl/aeto:{{ .Tag }}"
      # - "kristofferahl/aeto:v{{ .Major }}"
      # - "kristofferahl/aeto:v{{ .Major }}.{{ .Minor }}"
      - "kristofferahl/aeto:latest"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^.vscode:"
      - "^hack:"
