# permissions for end users to edit blueprints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: blueprint-editor-role
rules:
- apiGroups:
  - core.aeto.net
  resources:
  - blueprints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.aeto.net
  resources:
  - blueprints/status
  verbs:
  - get
