# permissions for end users to view certificates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificate-viewer-role
rules:
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificates/status
  verbs:
  - get
