# permissions for end users to view certificateconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificateconnector-viewer-role
rules:
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificateconnectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificateconnectors/status
  verbs:
  - get
