# permissions for end users to edit certificateconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificateconnector-editor-role
rules:
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificateconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificateconnectors/status
  verbs:
  - get
