# permissions for end users to view eventstreamchunks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventstreamchunk-viewer-role
rules:
- apiGroups:
  - event.aeto.net
  resources:
  - eventstreamchunks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - event.aeto.net
  resources:
  - eventstreamchunks/status
  verbs:
  - get
