# permissions for end users to view resourcesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourceset-viewer-role
rules:
- apiGroups:
  - core.aeto.net
  resources:
  - resourcesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.aeto.net
  resources:
  - resourcesets/status
  verbs:
  - get
