# permissions for end users to view resourcetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcetemplate-viewer-role
rules:
- apiGroups:
  - core.aeto.net
  resources:
  - resourcetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.aeto.net
  resources:
  - resourcetemplates/status
  verbs:
  - get
