
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificate
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificateconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificateconnectors/finalizers
  verbs:
  - update
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificateconnectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificates/finalizers
  verbs:
  - update
- apiGroups:
  - acm.aws.aeto.net
  resources:
  - certificates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.aeto.net
  resources:
  - blueprints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.aeto.net
  resources:
  - blueprints/finalizers
  verbs:
  - update
- apiGroups:
  - core.aeto.net
  resources:
  - blueprints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.aeto.net
  resources:
  - resourcesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.aeto.net
  resources:
  - resourcesets/finalizers
  verbs:
  - update
- apiGroups:
  - core.aeto.net
  resources:
  - resourcesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.aeto.net
  resources:
  - resourcetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.aeto.net
  resources:
  - resourcetemplates/finalizers
  verbs:
  - update
- apiGroups:
  - core.aeto.net
  resources:
  - resourcetemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.aeto.net
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.aeto.net
  resources:
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - core.aeto.net
  resources:
  - tenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route53.aws.aeto.net
  resources:
  - hostedzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route53.aws.aeto.net
  resources:
  - hostedzones/finalizers
  verbs:
  - update
- apiGroups:
  - route53.aws.aeto.net
  resources:
  - hostedzones/status
  verbs:
  - get
  - patch
  - update
