---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-alb
  namespace: kube-system
  annotations:
    aeto.net/controlled: "true"
    acm.aws.aeto.net/static-certificate-arn: ""
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: ""
    alb.ingress.kubernetes.io/actions.ping: '{"Type": "fixed-response", "FixedResponseConfig": {"ContentType":"text/plain", "StatusCode":"200", "MessageBody":"Pong"}}'
spec:
  rules:
    - host: loadbalancer.aeto.net
      http:
        paths:
          - path: /ping
            pathType: Exact
            backend:
              service:
                name: ping
                port:
                  name: use-annotation

---
apiVersion: acm.aws.aeto.net/v1alpha1
kind: CertificateConnector
metadata:
  name: alb-ingress-certificateconnector
  namespace: aeto
spec:
  ingress:
    connector: alb.ingress.kubernetes.io
    selector:
      namespaces:
        - kube-system
      labels: {}
      annotations:
        kubernetes.io/ingress.class: alb
  certificates:
    selector:
      namespaces:
        - aeto
      labels: {}
      annotations:
        aeto.net/controlled: "true"
