apiVersion: core.aeto.net/v1alpha1
kind: ResourceTemplate
metadata:
  name: resourcetemplate-sample
spec:
  raw:
    - |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{ .Namespace }}
      labels:
        app.kubernetes.io/tenant: "{{ .Key }}"
      annotations:
        aeto.net/controlled: true
