apiVersion: core.aeto.net/v1alpha1
kind: Blueprint
metadata:
  name: default
spec:
  resourceNamePrefix: tenant-
  resources:
    - name: namespace
      template: default-namespace-template
    - name: network_policy
      template: default-network-policy-template
    - name: limit_range
      template: default-limit-range-template
      parameters:
        - name: DefaultCpuLimit
          value: 200m
        - name: DefaultMemoryLimit
          value: 200Mi
    - name: hosted_zone
      template: default-route53-hostedzone-template
      parameters:
        - name: ParentHostedZoneName
          value: aeto.net
    - name: certificate
      template: default-acm-certificate-template
      parameters:
        - name: DomainName
          valueFrom:
            blueprint:
              resourceGroup: hosted_zone
              jsonPath: .resources[0].spec.name
        - name: HostedZoneId
          valueFrom:
            resource:
              apiVersion: route53.aws.aeto.net/v1alpha1
              kind: HostedZone
              name: "$TENANT_NAME"
              namespace: "$OPERATOR_NAMESPACE"
              jsonPath: .status.id
