apiVersion: core.aeto.net/v1alpha1
kind: ResourceTemplate
metadata:
  name: default-network-policy-template
spec:
  rules:
    name: keep
    namespace: tenant
  parameters: []
  resources:
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: "{{ .Name }}-allow-all-ingress"
      spec:
        podSelector: {}
        ingress:
          - {}
        policyTypes:
          - Ingress
