apiVersion: core.aeto.net/v1alpha1
kind: ResourceTemplate
metadata:
  name: default-namespace-template
spec:
  rules:
    name: tenant
    namespace: tenant
  parameters: []
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: "injected"
        labels:
          app.net/tenant: "injected"
        annotations:
          aeto.net/controlled: "injected"
