namespace: aeto
resources:
  - operator-namespace.yaml
  - default-blueprint.yaml
  - default-namespace-template.yaml
  - default-network-policy-template.yaml
  - default-limit-range-template.yaml
  - default-route53-hostedzone-template.yaml
  - default-acm-certificate-template.yaml
  - default-landing-page-template.yaml
